<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  export let inputTokens: number = 0;
  export let outputTokens: number = 0;
  export let numberOfRequests: number = 1;

  let scenarioNote: string = '';

  const dispatch = createEventDispatcher();

  const usagePresets = {
    Light: { input: 500, output: 200, requests: 10 },
    Medium: { input: 1500, output: 800, requests: 50 },
    Heavy: { input: 4000, output: 2000, requests: 200 },
  };

  const scenarioPresets = {
    Chatbot: { input: 800, output: 300, note: "Typical 100-500 req/day" },
    ContentGeneration: { input: 300, output: 1200, note: "Typical 20-100 req/day" },
    CodeAssistant: { input: 2000, output: 800, note: "Typical 30-150 req/day" },
    DataAnalysis: { input: 5000, output: 1500, note: "Typical 10-50 req/day" },
  };

  function applyUsagePreset(presetName: keyof typeof usagePresets) {
    const preset = usagePresets[presetName];
    inputTokens = preset.input;
    outputTokens = preset.output;
    numberOfRequests = preset.requests;
    scenarioNote = ''; 
    handleChange();
  }

  function applyScenarioPreset(presetName: keyof typeof scenarioPresets) {
    const preset = scenarioPresets[presetName];
    inputTokens = preset.input;
    outputTokens = preset.output;
    numberOfRequests = 1; 
    scenarioNote = preset.note;
    handleChange();
  }

  function handleChange() {
    if (numberOfRequests < 1) {
      numberOfRequests = 1;
    }
    dispatch('valueChange', { inputTokens, outputTokens, numberOfRequests });
  }
</script>

<div class="calculator-panel">
  <div class="calculator-header">
    <h3>⚙️ Usage Calculator</h3>
    <p class="calculator-subtitle">Configure your usage parameters</p>
  </div>
  
  <div class="manual-inputs">
    <div class="input-group">
      <label for="input-tokens">
        💬 Input Tokens (per request)
        <span class="input-hint">Words going into the model</span>
      </label>
      <div class="input-wrapper">
        <input type="number" id="input-tokens" bind:value={inputTokens} on:input={handleChange} min="0" placeholder="1000" />
        <span class="input-unit">tokens</span>
      </div>
    </div>
    <div class="input-group">
      <label for="output-tokens">
        📤 Output Tokens (per request)
        <span class="input-hint">Words generated by the model</span>
      </label>
      <div class="input-wrapper">
        <input type="number" id="output-tokens" bind:value={outputTokens} on:input={handleChange} min="0" placeholder="500" />
        <span class="input-unit">tokens</span>
      </div>
    </div>
    <div class="input-group">
      <label for="num-requests">
        🔢 Number of Requests
        <span class="input-hint">Total API calls you'll make</span>
      </label>
      <div class="input-wrapper">
        <input type="number" id="num-requests" bind:value={numberOfRequests} on:input={handleChange} min="1" placeholder="100" />
        <span class="input-unit">requests</span>
      </div>
    </div>
  </div>

  <div class="presets-section">
    <div class="presets-group">
      <h4>Bulk Usage Presets</h4>
      <div class="preset-buttons">
        {#each Object.entries(usagePresets) as [presetName, presetDetails] (presetName)}
          <button class="preset-button" on:click={() => applyUsagePreset(presetName as keyof typeof usagePresets)}>
            {presetName} ({presetDetails.requests.toLocaleString()} req)
          </button>
        {/each}
      </div>
    </div>

    <div class="presets-group">
      <h4>Single Request Scenario Presets</h4>
      <div class="preset-buttons">
        {#each Object.entries(scenarioPresets) as [presetName] (presetName)}
          <button class="preset-button" on:click={() => applyScenarioPreset(presetName as keyof typeof scenarioPresets)}>
            {presetName}
          </button>
        {/each}
      </div>
      {#if scenarioNote}
        <div class="scenario-note">
          <small>{scenarioNote}</small>
        </div>
      {/if}
    </div>
  </div>
</div>

<style>
  .calculator-panel {
    background: var(--card-bg);
    border: 1px solid var(--border-color);
    border-radius: 12px;
    padding: 1.5rem;
    box-shadow: var(--shadow);
    transition: all 0.3s ease;
  }

  .calculator-panel:hover {
    box-shadow: var(--shadow-lg);
  }

  .calculator-header {
    text-align: center;
    margin-bottom: 2rem;
    padding-bottom: 1rem;
    border-bottom: 2px solid var(--border-light);
  }

  .calculator-header h3 {
    margin: 0 0 0.5rem 0;
    font-size: 1.25rem;
    font-weight: 700;
    color: var(--text-color);
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
  }

  .calculator-subtitle {
    margin: 0;
    font-size: 0.875rem;
    color: var(--text-secondary);
    font-weight: 500;
  }

  .manual-inputs {
    margin-bottom: 2rem;
  }

  .input-group {
    display: flex;
    flex-direction: column;
    margin-bottom: 1.5rem;
  }

  .input-group label {
    font-size: 0.875rem;
    font-weight: 600;
    color: var(--text-color);
    margin-bottom: 0.75rem;
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
  }

  .input-hint {
    font-size: 0.75rem;
    font-weight: 400;
    color: var(--text-secondary);
    font-style: italic;
  }

  .input-wrapper {
    position: relative;
    display: flex;
    align-items: center;
  }

  .input-group input[type="number"] {
    width: 100%;
    padding: 0.875rem 4.5rem 0.875rem 1rem;
    border: 2px solid var(--input-border-color);
    border-radius: 8px;
    background-color: var(--input-bg);
    color: var(--text-color);
    font-size: 1rem;
    font-weight: 500;
    transition: all 0.2s ease;
  }

  .input-unit {
    position: absolute;
    right: 1rem;
    font-size: 0.75rem;
    color: var(--text-secondary);
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    pointer-events: none;
  }

  .input-group input[type="number"]:focus {
    border-color: var(--input-focus-border-color);
    box-shadow: var(--input-focus-box-shadow);
    outline: none;
    transform: translateY(-1px);
  }

  .input-group input[type="number"]:hover {
    border-color: var(--primary-light);
  }

  .presets-section {
    display: grid;
    grid-template-columns: 1fr;
    gap: 1.5rem;
  }

  .presets-group {
    padding: 1.5rem;
    background: var(--background-secondary);
    border-radius: 10px;
    border: 1px solid var(--border-light);
  }

  .presets-group h4 {
    margin: 0 0 1rem 0;
    font-size: 1rem;
    font-weight: 600;
    color: var(--text-color);
    display: flex;
    align-items: center;
    gap: 0.5rem;
  }

  .presets-group h4::before {
    content: '⚡';
    font-size: 1.2rem;
  }

  .preset-buttons {
    display: flex;
    flex-wrap: wrap;
    gap: 0.75rem;
  }

  .preset-button {
    padding: 0.75rem 1rem;
    border: 2px solid var(--border-color);
    background-color: var(--card-bg);
    color: var(--text-color);
    border-radius: 8px;
    cursor: pointer;
    font-weight: 500;
    font-size: 0.875rem;
    transition: all 0.2s ease;
    position: relative;
    overflow: hidden;
  }

  .preset-button:hover {
    background-color: var(--primary-color);
    color: white;
    border-color: var(--primary-color);
    transform: translateY(-2px);
    box-shadow: var(--shadow);
  }

  .preset-button:active {
    transform: translateY(0);
  }

  .scenario-note {
    margin-top: 1rem;
    padding: 0.75rem;
    background-color: var(--card-bg);
    border-radius: 6px;
    border-left: 3px solid var(--accent-color);
    font-size: 0.8rem;
    color: var(--text-secondary);
    font-style: italic;
  }

  /* Enhanced responsive design */
  @media (max-width: 1024px) {
    .presets-section {
      grid-template-columns: 1fr;
    }
  }

  @media (max-width: 768px) {
    .calculator-panel {
      padding: 1rem;
    }

    .input-group {
      margin-bottom: 1rem;
    }

    .preset-buttons {
      gap: 0.5rem;
    }

    .preset-button {
      padding: 0.6rem 0.8rem;
      font-size: 0.8rem;
    }
  }
</style>
